[package]
name = "softui"
version = "0.1.0"
edition = "2021"

[dependencies]
window = { version = "0.1.0", path = "../window" }
mini = { version = "0.1.0", path = "../mini" }
crossbeam-queue = "0.3.11"
# fontdue = { version = "0.7.3", features = ["parallel"] }
fontdue = { version = "0.9.0" }
