[package]
name = "softui"
version = "0.1.0"
edition = "2021"

[features]
svg = ["dep:resvg"]

[dependencies]
crossbeam-queue = "0.3.11"
# fontdue = { version = "0.7.3", features = ["parallel"] }
fontdue = { version = "0.9.0" }
glfw = "0.58.0"
mini = { git = "https://github.com/zx3no/mini", version = "0.1.0" }
minifb = "0.27.0"
resvg = { version = "0.42.0", optional = true }
# softui_proc = { version = "0.1.0", path = "softui_proc" }

[target.windows.dependencies]
# window = { version = "0.1.0", path = "../window" }
# mini = { version = "0.1.0", path = "../mini" }


[target."cfg(not(windows))".dependencies]
winit = "0.30.5"
